/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CallerRole {
  'gardenCenterMemberships' : Array<GardenCenterId>,
  'isCustomer' : boolean,
  'isPlatformAdmin' : boolean,
}
export interface Category {
  'id' : CategoryId,
  'name' : string,
  'description' : string,
  'parentCategoryId' : [] | [CategoryId],
}
export type CategoryId = bigint;
export interface CategoryWithSubcategories {
  'category' : Category,
  'subcategories' : Array<CategoryWithSubcategories>,
}
export interface FolderListing {
  'rootDirectories' : Array<string>,
  'documentationDirectories' : Array<string>,
  'toolsDirectories' : Array<string>,
  'backendDirectories' : Array<string>,
  'frontendDirectories' : Array<string>,
  'deploymentDirectories' : Array<string>,
}
export type GardenCenterId = bigint;
export interface Product {
  'id' : ProductId,
  'categoryId' : CategoryId,
  'active' : boolean,
  'imageUrls' : Array<string>,
  'name' : string,
  'gardenCenterId' : GardenCenterId,
  'description' : string,
  'parentCategoryId' : [] | [CategoryId],
  'stock' : bigint,
  'priceCents' : bigint,
}
export type ProductId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[string, string, [] | [CategoryId]], CategoryId>,
  'addGardenCenterMember' : ActorMethod<[GardenCenterId, Principal], undefined>,
  'addProduct' : ActorMethod<
    [string, string, CategoryId, bigint, bigint, GardenCenterId, Array<string>],
    ProductId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkUpdateStocks' : ActorMethod<
    [Array<[ProductId, GardenCenterId, bigint]>],
    undefined
  >,
  'checkUserRole' : ActorMethod<[Principal], UserRole>,
  'createGardenCenter' : ActorMethod<[string, string], GardenCenterId>,
  'getActiveProducts' : ActorMethod<[], Array<Product>>,
  'getCallerRole' : ActorMethod<[], CallerRole>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getCategoryByName' : ActorMethod<[string], [] | [Category]>,
  'getCategoryPath' : ActorMethod<[CategoryId], Array<Category>>,
  'getFullCategoryTaxonomy' : ActorMethod<[], Array<CategoryWithSubcategories>>,
  'getParsedFolderListing' : ActorMethod<[], FolderListing>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getProductsForCategory' : ActorMethod<[CategoryId], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantAdminAccess' : ActorMethod<[Principal], undefined>,
  'grantUserAccess' : ActorMethod<[Principal], undefined>,
  'initializeSeedData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeGardenCenter' : ActorMethod<[GardenCenterId], undefined>,
  'removeGardenCenterMember' : ActorMethod<
    [GardenCenterId, Principal],
    undefined
  >,
  'revokeAccess' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedDefaultCategories' : ActorMethod<[], undefined>,
  'updateGardenCenter' : ActorMethod<
    [GardenCenterId, string, string],
    undefined
  >,
  'upsertProductStock' : ActorMethod<
    [ProductId, GardenCenterId, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];