/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CategoryWithSubcategories = IDL.Rec();
export const CategoryId = IDL.Nat;
export const GardenCenterId = IDL.Nat;
export const ProductId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'categoryId' : CategoryId,
  'active' : IDL.Bool,
  'imageUrls' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'gardenCenterId' : GardenCenterId,
  'description' : IDL.Text,
  'parentCategoryId' : IDL.Opt(CategoryId),
  'stock' : IDL.Nat,
  'priceCents' : IDL.Nat,
});
export const CallerRole = IDL.Record({
  'gardenCenterMemberships' : IDL.Vec(GardenCenterId),
  'isCustomer' : IDL.Bool,
  'isPlatformAdmin' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Category = IDL.Record({
  'id' : CategoryId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'parentCategoryId' : IDL.Opt(CategoryId),
});
CategoryWithSubcategories.fill(
  IDL.Record({
    'category' : Category,
    'subcategories' : IDL.Vec(CategoryWithSubcategories),
  })
);

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(CategoryId)],
      [CategoryId],
      [],
    ),
  'addGardenCenterMember' : IDL.Func([GardenCenterId, IDL.Principal], [], []),
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        CategoryId,
        IDL.Nat,
        IDL.Nat,
        GardenCenterId,
        IDL.Vec(IDL.Text),
      ],
      [ProductId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkUpdateStocks' : IDL.Func(
      [IDL.Vec(IDL.Tuple(ProductId, GardenCenterId, IDL.Nat))],
      [],
      [],
    ),
  'checkUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
  'createGardenCenter' : IDL.Func([IDL.Text, IDL.Text], [GardenCenterId], []),
  'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerRole' : IDL.Func([], [CallerRole], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getCategoryByName' : IDL.Func([IDL.Text], [IDL.Opt(Category)], ['query']),
  'getCategoryPath' : IDL.Func([CategoryId], [IDL.Vec(Category)], ['query']),
  'getFullCategoryTaxonomy' : IDL.Func(
      [],
      [IDL.Vec(CategoryWithSubcategories)],
      ['query'],
    ),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getProductsForCategory' : IDL.Func(
      [CategoryId],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantAdminAccess' : IDL.Func([IDL.Principal], [], []),
  'grantUserAccess' : IDL.Func([IDL.Principal], [], []),
  'initializeSeedData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeGardenCenter' : IDL.Func([GardenCenterId], [], []),
  'removeGardenCenterMember' : IDL.Func(
      [GardenCenterId, IDL.Principal],
      [],
      [],
    ),
  'revokeAccess' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedDefaultCategories' : IDL.Func([], [], []),
  'updateGardenCenter' : IDL.Func([GardenCenterId, IDL.Text, IDL.Text], [], []),
  'upsertProductStock' : IDL.Func([ProductId, GardenCenterId, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CategoryWithSubcategories = IDL.Rec();
  const CategoryId = IDL.Nat;
  const GardenCenterId = IDL.Nat;
  const ProductId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'categoryId' : CategoryId,
    'active' : IDL.Bool,
    'imageUrls' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'gardenCenterId' : GardenCenterId,
    'description' : IDL.Text,
    'parentCategoryId' : IDL.Opt(CategoryId),
    'stock' : IDL.Nat,
    'priceCents' : IDL.Nat,
  });
  const CallerRole = IDL.Record({
    'gardenCenterMemberships' : IDL.Vec(GardenCenterId),
    'isCustomer' : IDL.Bool,
    'isPlatformAdmin' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Category = IDL.Record({
    'id' : CategoryId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'parentCategoryId' : IDL.Opt(CategoryId),
  });
  CategoryWithSubcategories.fill(
    IDL.Record({
      'category' : Category,
      'subcategories' : IDL.Vec(CategoryWithSubcategories),
    })
  );
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(CategoryId)],
        [CategoryId],
        [],
      ),
    'addGardenCenterMember' : IDL.Func([GardenCenterId, IDL.Principal], [], []),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          CategoryId,
          IDL.Nat,
          IDL.Nat,
          GardenCenterId,
          IDL.Vec(IDL.Text),
        ],
        [ProductId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkUpdateStocks' : IDL.Func(
        [IDL.Vec(IDL.Tuple(ProductId, GardenCenterId, IDL.Nat))],
        [],
        [],
      ),
    'checkUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
    'createGardenCenter' : IDL.Func([IDL.Text, IDL.Text], [GardenCenterId], []),
    'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerRole' : IDL.Func([], [CallerRole], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getCategoryByName' : IDL.Func([IDL.Text], [IDL.Opt(Category)], ['query']),
    'getCategoryPath' : IDL.Func([CategoryId], [IDL.Vec(Category)], ['query']),
    'getFullCategoryTaxonomy' : IDL.Func(
        [],
        [IDL.Vec(CategoryWithSubcategories)],
        ['query'],
      ),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getProductsForCategory' : IDL.Func(
        [CategoryId],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantAdminAccess' : IDL.Func([IDL.Principal], [], []),
    'grantUserAccess' : IDL.Func([IDL.Principal], [], []),
    'initializeSeedData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeGardenCenter' : IDL.Func([GardenCenterId], [], []),
    'removeGardenCenterMember' : IDL.Func(
        [GardenCenterId, IDL.Principal],
        [],
        [],
      ),
    'revokeAccess' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedDefaultCategories' : IDL.Func([], [], []),
    'updateGardenCenter' : IDL.Func(
        [GardenCenterId, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'upsertProductStock' : IDL.Func(
        [ProductId, GardenCenterId, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };