/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CallerRole {
  'gardenCenterMemberships' : Array<GardenCenterId>,
  'isCustomer' : boolean,
  'isPlatformAdmin' : boolean,
}
export interface Category {
  'id' : CategoryId,
  'name' : string,
  'description' : string,
}
export type CategoryId = bigint;
export interface GardenCenter {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'teamMembers' : Array<TeamMember>,
  'enabled' : boolean,
  'location' : string,
}
export type GardenCenterId = bigint;
export type OrderId = bigint;
export interface OrderItem {
  'pricePerItem' : bigint,
  'productId' : ProductId,
  'quantity' : bigint,
}
export interface Product {
  'id' : ProductId,
  'categoryId' : CategoryId,
  'active' : boolean,
  'imageUrls' : Array<string>,
  'name' : string,
  'gardenCenterId' : GardenCenterId,
  'description' : string,
  'stock' : bigint,
  'priceCents' : bigint,
}
export type ProductId = bigint;
export interface TeamMember { 'principal' : Principal, 'enabled' : boolean }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[string, string], CategoryId>,
  'addGardenCenterMember' : ActorMethod<[GardenCenterId, Principal], undefined>,
  'addProduct' : ActorMethod<
    [string, string, CategoryId, bigint, bigint, GardenCenterId, Array<string>],
    ProductId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGardenCenter' : ActorMethod<[string, string], GardenCenterId>,
  'disableGardenCenterMember' : ActorMethod<
    [GardenCenterId, Principal],
    undefined
  >,
  'enableGardenCenterMember' : ActorMethod<
    [GardenCenterId, Principal],
    undefined
  >,
  'getActiveProducts' : ActorMethod<[], Array<Product>>,
  'getCallerRole' : ActorMethod<[], CallerRole>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getGardenCenter' : ActorMethod<[GardenCenterId], GardenCenter>,
  'getGardenCenters' : ActorMethod<[], Array<GardenCenter>>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getProductsForCategory' : ActorMethod<[CategoryId], Array<Product>>,
  'getProductsForGardenCenter' : ActorMethod<[GardenCenterId], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeSeedData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[Array<OrderItem>], OrderId>,
  'removeGardenCenter' : ActorMethod<[GardenCenterId], undefined>,
  'removeGardenCenterMember' : ActorMethod<
    [GardenCenterId, Principal],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'toggleProductActive' : ActorMethod<[ProductId, boolean], undefined>,
  'updateGardenCenter' : ActorMethod<
    [GardenCenterId, string, string],
    undefined
  >,
  'updateProduct' : ActorMethod<
    [ProductId, string, string, CategoryId, bigint, bigint, Array<string>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];