/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CategoryId = IDL.Nat;
export const GardenCenterId = IDL.Nat;
export const ProductId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'categoryId' : CategoryId,
  'active' : IDL.Bool,
  'imageUrls' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'gardenCenterId' : GardenCenterId,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'priceCents' : IDL.Nat,
});
export const CallerRole = IDL.Record({
  'gardenCenterMemberships' : IDL.Vec(GardenCenterId),
  'isCustomer' : IDL.Bool,
  'isPlatformAdmin' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Category = IDL.Record({
  'id' : CategoryId,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const TeamMember = IDL.Record({
  'principal' : IDL.Principal,
  'enabled' : IDL.Bool,
});
export const GardenCenter = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'teamMembers' : IDL.Vec(TeamMember),
  'enabled' : IDL.Bool,
  'location' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'pricePerItem' : IDL.Nat,
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const OrderId = IDL.Nat;

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([IDL.Text, IDL.Text], [CategoryId], []),
  'addGardenCenterMember' : IDL.Func([GardenCenterId, IDL.Principal], [], []),
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        CategoryId,
        IDL.Nat,
        IDL.Nat,
        GardenCenterId,
        IDL.Vec(IDL.Text),
      ],
      [ProductId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGardenCenter' : IDL.Func([IDL.Text, IDL.Text], [GardenCenterId], []),
  'disableGardenCenterMember' : IDL.Func(
      [GardenCenterId, IDL.Principal],
      [],
      [],
    ),
  'enableGardenCenterMember' : IDL.Func(
      [GardenCenterId, IDL.Principal],
      [],
      [],
    ),
  'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerRole' : IDL.Func([], [CallerRole], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getGardenCenter' : IDL.Func([GardenCenterId], [GardenCenter], ['query']),
  'getGardenCenters' : IDL.Func([], [IDL.Vec(GardenCenter)], ['query']),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getProductsForCategory' : IDL.Func(
      [CategoryId],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductsForGardenCenter' : IDL.Func(
      [GardenCenterId],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSeedData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Vec(OrderItem)], [OrderId], []),
  'removeGardenCenter' : IDL.Func([GardenCenterId], [], []),
  'removeGardenCenterMember' : IDL.Func(
      [GardenCenterId, IDL.Principal],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'toggleProductActive' : IDL.Func([ProductId, IDL.Bool], [], []),
  'updateGardenCenter' : IDL.Func([GardenCenterId, IDL.Text, IDL.Text], [], []),
  'updateProduct' : IDL.Func(
      [
        ProductId,
        IDL.Text,
        IDL.Text,
        CategoryId,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CategoryId = IDL.Nat;
  const GardenCenterId = IDL.Nat;
  const ProductId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'categoryId' : CategoryId,
    'active' : IDL.Bool,
    'imageUrls' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'gardenCenterId' : GardenCenterId,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'priceCents' : IDL.Nat,
  });
  const CallerRole = IDL.Record({
    'gardenCenterMemberships' : IDL.Vec(GardenCenterId),
    'isCustomer' : IDL.Bool,
    'isPlatformAdmin' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Category = IDL.Record({
    'id' : CategoryId,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const TeamMember = IDL.Record({
    'principal' : IDL.Principal,
    'enabled' : IDL.Bool,
  });
  const GardenCenter = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'teamMembers' : IDL.Vec(TeamMember),
    'enabled' : IDL.Bool,
    'location' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'pricePerItem' : IDL.Nat,
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const OrderId = IDL.Nat;
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([IDL.Text, IDL.Text], [CategoryId], []),
    'addGardenCenterMember' : IDL.Func([GardenCenterId, IDL.Principal], [], []),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          CategoryId,
          IDL.Nat,
          IDL.Nat,
          GardenCenterId,
          IDL.Vec(IDL.Text),
        ],
        [ProductId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGardenCenter' : IDL.Func([IDL.Text, IDL.Text], [GardenCenterId], []),
    'disableGardenCenterMember' : IDL.Func(
        [GardenCenterId, IDL.Principal],
        [],
        [],
      ),
    'enableGardenCenterMember' : IDL.Func(
        [GardenCenterId, IDL.Principal],
        [],
        [],
      ),
    'getActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerRole' : IDL.Func([], [CallerRole], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getGardenCenter' : IDL.Func([GardenCenterId], [GardenCenter], ['query']),
    'getGardenCenters' : IDL.Func([], [IDL.Vec(GardenCenter)], ['query']),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getProductsForCategory' : IDL.Func(
        [CategoryId],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsForGardenCenter' : IDL.Func(
        [GardenCenterId],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSeedData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([IDL.Vec(OrderItem)], [OrderId], []),
    'removeGardenCenter' : IDL.Func([GardenCenterId], [], []),
    'removeGardenCenterMember' : IDL.Func(
        [GardenCenterId, IDL.Principal],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'toggleProductActive' : IDL.Func([ProductId, IDL.Bool], [], []),
    'updateGardenCenter' : IDL.Func(
        [GardenCenterId, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateProduct' : IDL.Func(
        [
          ProductId,
          IDL.Text,
          IDL.Text,
          CategoryId,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };